name: main

on:
  push:
    branches: [main]
  pull_request:

env:
  TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
  TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
  TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}

jobs:
  run-commands:
    strategy:
      matrix:
        command:
          - name: test
            run: pnpm test --parallel --color
          # - lint
          # - typecheck
          # - build
      fail-fast: false
    name: ${{ matrix.command.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "16"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: ${{ matrix.command.run }}
