name: the

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
  TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
  TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}

jobs:
  ci:
    strategy:
      matrix:
        script-name: [test, lint, typecheck]
      fail-fast: false
    name: ${{ matrix.script-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run ${{ matrix.script-name }}
